# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_control.ui'
#
# Created: Mon Nov 19 17:34:20 2012
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Control(object):
    def setupUi(self, Control):
        Control.setObjectName(_fromUtf8("Control"))
        Control.resize(600, 120)
        Control.setMinimumSize(QtCore.QSize(600, 120))
        Control.setMaximumSize(QtCore.QSize(600, 120))
        self.verticalLayout_3 = QtGui.QVBoxLayout(Control)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.frame = QtGui.QFrame(Control)
        self.frame.setMaximumSize(QtCore.QSize(16777215, 37))
        self.frame.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame.setFrameShadow(QtGui.QFrame.Plain)
        self.frame.setLineWidth(0)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(5, 2, 5, 2)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.gridFrame = QtGui.QFrame(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gridFrame.sizePolicy().hasHeightForWidth())
        self.gridFrame.setSizePolicy(sizePolicy)
        self.gridFrame.setObjectName(_fromUtf8("gridFrame"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.gridFrame)
        self.horizontalLayout_6.setMargin(0)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.play = QtGui.QToolButton(self.gridFrame)
        self.play.setMinimumSize(QtCore.QSize(22, 24))
        self.play.setMaximumSize(QtCore.QSize(16777215, 24))
        self.play.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/right.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.play.setIcon(icon)
        self.play.setObjectName(_fromUtf8("play"))
        self.horizontalLayout_6.addWidget(self.play)
        self.pause = QtGui.QToolButton(self.gridFrame)
        self.pause.setMinimumSize(QtCore.QSize(22, 24))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/pause.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pause.setIcon(icon1)
        self.pause.setObjectName(_fromUtf8("pause"))
        self.horizontalLayout_6.addWidget(self.pause)
        self.stop = QtGui.QToolButton(self.gridFrame)
        self.stop.setMinimumSize(QtCore.QSize(22, 24))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/stop.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.stop.setIcon(icon2)
        self.stop.setObjectName(_fromUtf8("stop"))
        self.horizontalLayout_6.addWidget(self.stop)
        self.line = QtGui.QFrame(self.gridFrame)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.horizontalLayout_6.addWidget(self.line)
        self.back = QtGui.QToolButton(self.gridFrame)
        self.back.setMinimumSize(QtCore.QSize(22, 24))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/backward.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.back.setIcon(icon3)
        self.back.setObjectName(_fromUtf8("back"))
        self.horizontalLayout_6.addWidget(self.back)
        self.forw = QtGui.QToolButton(self.gridFrame)
        self.forw.setMinimumSize(QtCore.QSize(22, 24))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/forward.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.forw.setIcon(icon4)
        self.forw.setObjectName(_fromUtf8("forw"))
        self.horizontalLayout_6.addWidget(self.forw)
        self.line_2 = QtGui.QFrame(self.gridFrame)
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.horizontalLayout_6.addWidget(self.line_2)
        self.snip_stop = QtGui.QToolButton(self.gridFrame)
        self.snip_stop.setMinimumSize(QtCore.QSize(22, 24))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/autostop.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.snip_stop.setIcon(icon5)
        self.snip_stop.setCheckable(True)
        self.snip_stop.setObjectName(_fromUtf8("snip_stop"))
        self.horizontalLayout_6.addWidget(self.snip_stop)
        self.horizontalLayout.addWidget(self.gridFrame)
        self.frame_4 = QtGui.QFrame(self.frame)
        self.frame_4.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setObjectName(_fromUtf8("frame_4"))
        self.horizontalLayout.addWidget(self.frame_4)
        self.frame_5 = QtGui.QFrame(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_5.sizePolicy().hasHeightForWidth())
        self.frame_5.setSizePolicy(sizePolicy)
        self.frame_5.setMinimumSize(QtCore.QSize(280, 0))
        self.frame_5.setMaximumSize(QtCore.QSize(280, 16777215))
        self.frame_5.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_5.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_5.setObjectName(_fromUtf8("frame_5"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.frame_5)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.snip_pre = QtGui.QToolButton(self.frame_5)
        self.snip_pre.setMinimumSize(QtCore.QSize(22, 24))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/previous.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.snip_pre.setIcon(icon6)
        self.snip_pre.setObjectName(_fromUtf8("snip_pre"))
        self.horizontalLayout_2.addWidget(self.snip_pre)
        self.snip_box = QtGui.QComboBox(self.frame_5)
        self.snip_box.setMinimumSize(QtCore.QSize(0, 24))
        self.snip_box.setMaximumSize(QtCore.QSize(16777215, 24))
        self.snip_box.setObjectName(_fromUtf8("snip_box"))
        self.horizontalLayout_2.addWidget(self.snip_box)
        self.snip_next = QtGui.QToolButton(self.frame_5)
        self.snip_next.setMinimumSize(QtCore.QSize(22, 24))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/next.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.snip_next.setIcon(icon7)
        self.snip_next.setObjectName(_fromUtf8("snip_next"))
        self.horizontalLayout_2.addWidget(self.snip_next)
        self.horizontalLayout.addWidget(self.frame_5)
        self.verticalLayout_3.addWidget(self.frame)
        self.frame_2 = QtGui.QFrame(Control)
        self.frame_2.setEnabled(True)
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 67))
        self.frame_2.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setLineWidth(0)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setContentsMargins(5, 0, 5, 0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.slider = QtGui.QSlider(self.frame_2)
        self.slider.setMaximum(10000)
        self.slider.setPageStep(100)
        self.slider.setOrientation(QtCore.Qt.Horizontal)
        self.slider.setObjectName(_fromUtf8("slider"))
        self.verticalLayout_2.addWidget(self.slider)
        self.snip_overview = QtGui.QLabel(self.frame_2)
        self.snip_overview.setMaximumSize(QtCore.QSize(16777215, 4))
        self.snip_overview.setText(_fromUtf8(""))
        self.snip_overview.setObjectName(_fromUtf8("snip_overview"))
        self.verticalLayout_2.addWidget(self.snip_overview)
        self.horizontalFrame = QtGui.QFrame(self.frame_2)
        self.horizontalFrame.setMinimumSize(QtCore.QSize(0, 25))
        self.horizontalFrame.setMaximumSize(QtCore.QSize(16777215, 25))
        self.horizontalFrame.setObjectName(_fromUtf8("horizontalFrame"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.horizontalFrame)
        self.horizontalLayout_3.setContentsMargins(5, 0, 5, 0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.time = QtGui.QLabel(self.horizontalFrame)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.time.setFont(font)
        self.time.setObjectName(_fromUtf8("time"))
        self.horizontalLayout_3.addWidget(self.time)
        self.frame_6 = QtGui.QFrame(self.horizontalFrame)
        self.frame_6.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_6.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_6.setLineWidth(0)
        self.frame_6.setObjectName(_fromUtf8("frame_6"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.frame_6)
        self.horizontalLayout_4.setMargin(0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_2 = QtGui.QLabel(self.frame_6)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_4.addWidget(self.label_2)
        self.speed = QtGui.QDoubleSpinBox(self.frame_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.speed.sizePolicy().hasHeightForWidth())
        self.speed.setSizePolicy(sizePolicy)
        self.speed.setMinimumSize(QtCore.QSize(0, 24))
        self.speed.setMaximumSize(QtCore.QSize(16777215, 24))
        self.speed.setMinimum(0.02)
        self.speed.setMaximum(20.0)
        self.speed.setSingleStep(0.05)
        self.speed.setProperty("value", 1.0)
        self.speed.setObjectName(_fromUtf8("speed"))
        self.horizontalLayout_4.addWidget(self.speed)
        self.horizontalLayout_3.addWidget(self.frame_6)
        self.verticalLayout_2.addWidget(self.horizontalFrame)
        self.verticalLayout_3.addWidget(self.frame_2)
        self.frame_3 = QtGui.QFrame(Control)
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 31))
        self.frame_3.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setLineWidth(0)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.frame_3)
        self.horizontalLayout_5.setMargin(2)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.load_stim = QtGui.QPushButton(self.frame_3)
        self.load_stim.setObjectName(_fromUtf8("load_stim"))
        self.horizontalLayout_5.addWidget(self.load_stim)
        self.configure = QtGui.QPushButton(self.frame_3)
        self.configure.setObjectName(_fromUtf8("configure"))
        self.horizontalLayout_5.addWidget(self.configure)
        self.verticalLayout_3.addWidget(self.frame_3)

        self.retranslateUi(Control)
        QtCore.QMetaObject.connectSlotsByName(Control)

    def retranslateUi(self, Control):
        Control.setWindowTitle(QtGui.QApplication.translate("Control", "Control", None, QtGui.QApplication.UnicodeUTF8))
        self.play.setToolTip(QtGui.QApplication.translate("Control", "Play", None, QtGui.QApplication.UnicodeUTF8))
        self.pause.setToolTip(QtGui.QApplication.translate("Control", "Pause", None, QtGui.QApplication.UnicodeUTF8))
        self.pause.setText(QtGui.QApplication.translate("Control", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.stop.setToolTip(QtGui.QApplication.translate("Control", "Stop", None, QtGui.QApplication.UnicodeUTF8))
        self.stop.setText(QtGui.QApplication.translate("Control", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.back.setToolTip(QtGui.QApplication.translate("Control", "4 seconds back", None, QtGui.QApplication.UnicodeUTF8))
        self.back.setText(QtGui.QApplication.translate("Control", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.forw.setToolTip(QtGui.QApplication.translate("Control", "4 seconds forward", None, QtGui.QApplication.UnicodeUTF8))
        self.forw.setText(QtGui.QApplication.translate("Control", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.snip_stop.setToolTip(QtGui.QApplication.translate("Control", "Stop after every snippet", None, QtGui.QApplication.UnicodeUTF8))
        self.snip_stop.setText(QtGui.QApplication.translate("Control", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.snip_pre.setToolTip(QtGui.QApplication.translate("Control", "Play previous snippet", None, QtGui.QApplication.UnicodeUTF8))
        self.snip_pre.setText(QtGui.QApplication.translate("Control", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.snip_box.setToolTip(QtGui.QApplication.translate("Control", "Select snippet", None, QtGui.QApplication.UnicodeUTF8))
        self.snip_next.setToolTip(QtGui.QApplication.translate("Control", "Play next snippet", None, QtGui.QApplication.UnicodeUTF8))
        self.snip_next.setText(QtGui.QApplication.translate("Control", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.time.setText(QtGui.QApplication.translate("Control", "0:00:00.000 / 0:00:00.000", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Control", "Speed:", None, QtGui.QApplication.UnicodeUTF8))
        self.speed.setToolTip(QtGui.QApplication.translate("Control", "Set speed", None, QtGui.QApplication.UnicodeUTF8))
        self.load_stim.setText(QtGui.QApplication.translate("Control", "Load stimulus", None, QtGui.QApplication.UnicodeUTF8))
        self.configure.setText(QtGui.QApplication.translate("Control", "Configure data", None, QtGui.QApplication.UnicodeUTF8))

import icons_rc
